### ISSUE TITLE
It's a trap!

### ISSUE THREAD

**Issue by stanleyqubit** [tewlwolow/AURA#14]
1. `coc "Hla Oad, Fatleg's Drop Off"`
2. Ok, it's a shack.
3. interiormain: `Enough statics. Cell type: cav`
4. What? It's a shack!
5. Look around. See trapdoor on the ground.
6. `unlock` trapdoor, climb down.
7. Oh..........

🤣 

So IA is confused and IE's gonna play `cav` type on that shack door when you go out, because that's what IA said. Wat do?

**Comment by tewlwolow** [comment]
Yeah I've just been ignoring this one 🗡️👯 buuut maybe we want to maintain a hardcoded list for such cases?
